CREATE TABLE IF NOT EXISTS PRODUCT
(
    id   INT,
    name  VARCHAR(100) NOT NULL,
    uuid  VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS MANY_TO_ONE_PRODUCT
(
    id     INTEGER PRIMARY KEY,
    product_id     INT
);